from wand.image import Image
from wand.color import Color

img1 = Image(filename='baseColorWand.jpg')
img2 = Image(filename='baseTexture.jpg')
img1.composite_channel(channel='undefined', image=img2, operator='blend', left=0, top=0)
img1.save(filename='.\\test\\undefined_blend.jpg')
img1.composite_channel(channel='rgb_channels', image=img2, operator='blend', left=0, top=0)
img1.save(filename='.\\test\\rgb_channels_blend.jpg')
img1.composite_channel(channel='all_channels', image=img2, operator='undefined', left=0, top=0)
img1.save(filename='.\\test\\all_channels_undefined.jpg')
# img = Image(filename='102.jpg')
# baseImage = Image(width=560, height=840, background=Color('red'))
# baseImage.save(filename='.\\test\\basecolor.jpg')
# img.composite_channel(channel='undefined', image=baseImage, operator='blend', left=0, top=0)
# img.save(filename='.\\test\\undefined_blend.jpg')
# img.composite_channel(channel='alpha', image=baseImage, operator='blend', left=0, top=0)
# img.save(filename='.\\test\\alpha_blend.jpg')
# img.composite_channel(channel='composite_channels', image=baseImage, operator='blend', left=0, top=0)
# img.save(filename='.\\test\\composite_channels_blend.jpg')
# img.composite_channel(channel='rgb_channels', image=baseImage, operator='blend', left=0, top=0)
# img.save(filename='.\\test\\rgb_channels_blend.jpg')
# img.composite_channel(channel='true_alpha', image=baseImage, operator='blend', left=0, top=0)
# img.save(filename='.\\test\\true_alpha_blend.jpg')
